apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-api
  namespace: ms-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-api
  template:
    metadata:
      labels:
        app: orders-api
    spec:
      containers:
        - name: orders-api
          image: amoreno20/orders-api:1.0
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: orders-config
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: orders-api
  namespace: ms-demo
spec:
  selector:
    app: orders-api
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
  type: NodePort